### ISSUE TITLE
Frontend Contribution

### ISSUE THREAD

**Issue by Ankk98** [JIITODC/jiitodc.github.io#10]
Discuss here your ideas on the frontend section.

We encourage contributions.

**Comment by weirdwiz** [comment]
I would like to suggest the font to something monospace

**Comment by Ankurk99** [comment]
Added top navigation bar and heading to the topics

**Comment by Ankk98** [comment]
@Ankurk99  Thanks. 
Merged PRs #37  #38 #39 .
You can start work on #41 .

**Comment by kcclemo** [comment]
The layout could be a bit more responsive. Maybe using CSS Grid, or a grid layout using percentages and media queries.

**Comment by Ankk98** [comment]
@kcclemo You are always welcome to experiment with the website to make it better.

**Comment by prox07** [comment]
I think ideas can be, with a little bit of work, shaped into issues. Let's do that. Closing this.
