### ISSUE TITLE
Convert jpg images to webp using a node module.

### ISSUE THREAD

**Issue by aayushmau5** [JIITODC/jiitodc.github.io#12]
Use a node module as a `dev-dependencies` which convert all the `.jpg` images present in `src/Photos/` to `.webp`.

Ref: https://yossiabramov.com/blog/converting-images-to-webp-with-node-js

**Comment by Reynadi531** [comment]
you just want to add node modules or the script too

**Comment by aayushmau5** [comment]
Both.

**Comment by sarthakm21** [comment]
Hi @aayushmau5. Can I work on this?

**Comment by aayushmau5** [comment]
Yeah sure. Go ahead.
