### ISSUE TITLE
remove unused CSS selectors

### ISSUE THREAD

**Issue by humancalico** [JIITODC/jiitodc.github.io#18]
There are some CSS selectors inside `src/routes/index.svelte` which are redundant and can be removed. These can be found by running the server (on running `npm run dev`). Some of these, at the time of writing this issue, are

```css
/home/humancalico/code/jiitodc.github.io/src/routes/index.svelte
Unused CSS selector ".logo-container.open .logo-front"
100:     }
101:
102:     .logo-container.open .logo-front{
         ^
103:       transform: none;
104:     }
/home/humancalico/code/jiitodc.github.io/src/routes/index.svelte
Unused CSS selector ".divider-big.open"
104:     }
105:
106:     .divider-big.open{
         ^
107:     visibility: hidden;
108:     }
```

**Comment by karanpatel2329** [comment]
i will fix this issue #18

**Comment by chamindujs** [comment]
I will remove all the unwanted css 👍.

**Comment by humancalico** [comment]
Thanks @chamindujs. Although to prevent duplicated efforts from contributors on the same issue try to pick issues that other contributors have not picked up already. For eg. you can pick #2 or #3 right now, if you face any difficulty while solving the issue or have no idea what to do you can comment on the respective issues and we'll help you out.
