### ISSUE TITLE
(ci) add `lighthouse-ci` as GitHub Actions

### ISSUE THREAD

**Issue by humancalico** [JIITODC/jiitodc.github.io#2]
ref: https://github.com/GoogleChrome/lighthouse-ci

**Comment by LeoAlvarenga** [comment]
Can you assign this to me?

**Comment by humancalico** [comment]
Sure @LeoAlvarenga!

**Comment by ayuushhh** [comment]
hello,can u guide me into what exactly we have to do here?

**Comment by humancalico** [comment]
@LeoAlvarenga are you still working on this?

**Comment by LeoAlvarenga** [comment]
@humancalico i do, but i'm having some problems with the commits.

**Comment by humancalico** [comment]
@LeoAlvarenga You can ask your questions here or at https://t.me/jiitodc
