### ISSUE TITLE
Images not scaling in the blog

### ISSUE THREAD

**Issue by weirdwiz** [JIITODC/jiitodc.github.io#23]
The images do not scale down in mobile, and appears huge on the desktop.

[Mobile](https://user-images.githubusercontent.com/24807435/94667713-cc8a6b80-032c-11eb-8259-6167d5012de0.jpg)

**Comment by ayuushhh** [comment]
hello , i would like to contribute to this issue . I am a beginner so can u please guide me into this?

**Comment by humancalico** [comment]
Sure @ayuushhh. There are some CSS selectors that need to be added/tweaked inside of https://github.com/JIITODC/jiitodc.github.io/blob/master/static/global.css file. You can refer to https://github.com/Charca/sapper-blog-template/blob/master/static/global.css for that. If you still have any questions you can ping me here or at https://t.me/jiitodc.

**Comment by weirdwiz** [comment]
@ayuushhh Do you have any progress on this issue?
