### ISSUE TITLE
Spelling and grammatical errors in "About Us' section

### ISSUE THREAD

**Issue by Ankurk99** [JIITODC/jiitodc.github.io#24]
There are some grammar and spelling mistakes in the "About Section". For example "undoubtedly" and "organization". Check for any other errors too.
___
Edit(@humancalico)
file to be changed: https://github.com/JIITODC/jiitodc.github.io/blob/master/src/routes/index.svelte

**Comment by HylkeReinders** [comment]
I would like to do this one. Is that possible?

This is my first time contributing to an open source project :)

**Comment by Saujanya0910** [comment]
Hey, I would like to contribute to this issue if that's possible. My first time contributing to an open-source project as well!

**Comment by sunilgknair051** [comment]
> 
> 
> There are some grammar and spelling mistakes in the "About Section". For example "undoubtedly" and "organization". Check for any other errors too.

My bad @Ankurk99 , I just corrected something before I could comment here.  !Sorry!

**Comment by Ankurk99** [comment]
@HylkeReinders @Saujanya0910 There are many other beginners friendly issues, you can take one from them too.

**Comment by Ankurk99** [comment]
> > There are some grammar and spelling mistakes in the "About Section". For example "undoubtedly" and "organization". Check for any other errors too.
> 
> My bad @Ankurk99 , I just corrected something before I could comment here. !Sorry!

No problem. But please try to ask first, before making any PR.

**Comment by weirdwiz** [comment]
Can we close this issue, I think it's fixed and

**Comment by humancalico** [comment]
> Can we close this issue, I think it's fixed and

IDTS @weirdwiz 

https://github.com/JIITODC/jiitodc.github.io/blob/7ac8699d58025b2945d5cd7964c0341281722d3b/src/routes/index.svelte#L197

**Comment by sunilgknair051** [comment]
"something that is undoubted is not doubted, while something that is undoubtable is not capable of being doubted"
There is an overlap of the meanings sometimes. Will correct if necessary.
