### ISSUE TITLE
Fix grammar

### ISSUE THREAD

**Issue by prox07** [JIITODC/jiitodc.github.io#25]
Certainly not the type of grammer one would expect. The content on this site must be **on point, no emoticons, and exceptionally formal**.

Fix [this](https://github.com/JIITODC/jiitodc.github.io/blob/a1da94a071c8807656acb484033da84963019f6c/index.html#L48).

**Comment by vinopaldimit** [comment]
Sent a PR. Tell me if there's anything else that needs to be changed.
