### ISSUE TITLE
Use any date library to Compare date.

### ISSUE THREAD

**Issue by aayushmau5** [JIITODC/jiitodc.github.io#28]
Change the `compareDate` function present in `src/routes/events.svelte` to compare date using any JS library that handles date. The date data is taken from `static/Data/events.json` with the specific input of `"formatDate": "19-9-2020"`. Right now the compareDate returns `false` even if it is in the future.

**Comment by divyanshsikarwar** [comment]
I have a doubt here, function should return true if the input date (prevDate) is a future date right ?

**Comment by aayushmau5** [comment]
Yes. You got that right.
