### ISSUE TITLE
Add missing links to team pages 

### ISSUE THREAD

**Issue by DelusionalOptimist** [JIITODC/jiitodc.github.io#39]
Previous year team pages don't have links to other team pages.
See: [team-2019 page](https://jodc.vercel.app/team-2019)
To navigate to other team pages one has to go to the [current team](https://jodc.vercel.app/team) page.
Linking the pages chronologically may help navigate.

Images given below will give a better idea of the suggested changes:-

The [team-2019](https://jodc.vercel.app/team-2019) page
![20201002-232939](https://user-images.githubusercontent.com/54525605/94956557-fea4f480-0509-11eb-8377-e0677f40d87a.jpg)

The [team](https://jodc.vercel.app/team) page
![20201002-222536](https://user-images.githubusercontent.com/54525605/94959559-06b36300-050f-11eb-96ad-0defe581f7c8.jpg)

**Comment by LeoAlvarenga** [comment]
Hey! i'd like to help, can you assign this to me?

**Comment by LeoAlvarenga** [comment]
Hey man! i'm just working on it right now, i'd like to know if you can label it as a valid hacktoberfest issue?
