### ISSUE TITLE
add Prettier plugin

### ISSUE THREAD

**Issue by humancalico** [JIITODC/jiitodc.github.io#4]
ref: https://github.com/sveltejs/prettier-plugin-svelte

**Comment by samarth-1729** [comment]
Hey,
Do you mean you want to format the whole code?
I would like to do it.

**Comment by humancalico** [comment]
@samarth-1729 Yes. This article (https://tiaan.dev/posts/eslint-and-prettier-setup-for-sapper/) gives a pretty good description of what is to be done IMO. Let me know if you face any difficulty while working on this

**Comment by samarth-1729** [comment]
Ok,
I'll look into it

**Comment by codybarr** [comment]
@humancalico I noticed this was stale. Submitted a PR: #44 .
