### ISSUE TITLE
Update Navbar

### ISSUE THREAD

**Issue by Ankk98** [JIITODC/jiitodc.github.io#41]
Navbar has too many sections:

1. Merge About Us, Team, How we started, Vision, Code of Conduct into one 
2. Remove News Section

Can change its colour also.

**Comment by swaager** [comment]
May i work on this issue?

**Comment by Ankk98** [comment]
Sure @swaager

**Comment by Ankk98** [comment]
![screenshot from 2018-10-21 10-24-14](https://user-images.githubusercontent.com/24476799/47263279-3c2a3600-d51c-11e8-9af0-41754b7d354e.png)

@swaager You have changed navbar in #42  but it still needs the following changes:
1. Remove news from the navbar
2. Contact occurs 2 times in navbar
3. Try having a menu in the centre of the page
4. Remove news section from page
5. Rearrange sections on the webpage
6. There is a typo in Members section heading
7. Create alternate colour coding in the background of sections to differentiate sections
(e.g. black-white)
8. Create a footer and move links into that part
9. In footer add Made by JODC and contributors

**Comment by Rohitkrops** [comment]
@swaager there is no reason to put that down thumb there. Contributions are counted later first is your attitude and behavior. 

Also if Maintainers have assigned a task to someone it's important to update '**Assignees **.

**Comment by kcclemo** [comment]
I'd be happy to tackle this if you assign it to me. Just seeing that despite comments, there has been no movement.

**Comment by Ankk98** [comment]
@kcclemo as @swaager said he is working on it, let us wait for some days for him to fix it.

**Comment by Ri2parna** [comment]
Is this issue still open?

**Comment by Ankk98** [comment]
@swaager Any updates on your work?
