### ISSUE TITLE
Images rendered over Navbar

### ISSUE THREAD

**Issue by arvindpunk** [JIITODC/jiitodc.github.io#50]
![image](https://user-images.githubusercontent.com/24990564/47295499-66b7e400-d62d-11e8-823b-931ffdd0a732.png)

This should not be the case. Image(s) should be rendered below the navbar.

## Steps to Reproduce the Problem
  1. Scroll down until image and navbar coincide.

Issue occurs on both desktop and mobile devices.

**Comment by Ankk98** [comment]
@arvindpunk  Thanks for informing about the issue.

**Comment by Ankk98** [comment]
Okay, it takes some time to reflect changes on GitHub pages.
