### ISSUE TITLE
Increase Animate On Scroll duration.

### ISSUE THREAD

**Issue by aayushmau5** [JIITODC/jiitodc.github.io#6]
On scrolling, animation happens too early. Increase the duration by bringing changes in `src/component/TeamComponent.svelte` and `src/component/EventComponent.svelte` file. Ref: https://github.com/michalsnik/aos

**Comment by therealansh** [comment]
hey @aayushmau5, can i work on this one? Thank you.

**Comment by aayushmau5** [comment]
Yeah sure. Go ahead.
