### ISSUE TITLE
Make navbar responsive

### ISSUE THREAD

**Issue by prox07** [JIITODC/jiitodc.github.io#60]
## Expected Behavior
**Hamburger menu on tablets and mobile screen.**

## Actual Behavior
**No such menu whatsoever on resizing the window.**

## Fixes
Define specific breakpoints for different screens, and implementing them not only for navbar, but all elements of the site.
Can use bootstrap to do so as well.
Or better yet, how about a **CSS Grid** revamp?

**Comment by JS-goose** [comment]
I'd be happy to tackle this for you 😺

**Comment by Ankk98** [comment]
Sure @JS-goose, go for it
