### ISSUE TITLE
Revamp User Interface

### ISSUE THREAD

**Issue by Ankk98** [JIITODC/jiitodc.github.io#63]
## Expected Behavior
The user interface should be simple, easy to understand, accessible and flawless.

## Actual Behavior
![screenshot from 2018-10-26 14-03-43](https://user-images.githubusercontent.com/24476799/47555138-aaaa3200-d928-11e8-809e-eb7d3ae07f69.png)

##Changes that are needed to be made:
1. Background Colour Combination is not good
2. An arrow is needed to be added that indicates scrolling
3. Make background full page, see the image.
4. No need of octocat on every section

**Comment by Ri2parna** [comment]
Arrow? Can you explain a bit?
