### ISSUE TITLE
Change navigation bar to show which page is active.

### ISSUE THREAD

**Issue by aayushmau5** [JIITODC/jiitodc.github.io#73]
The idea is to gray out all the navigation links and only highlight the active link.

**Comment by JoelLau** [comment]
hi, can I take this up as part of hacktoberfest?

**Comment by aayushmau5** [comment]
Yeah, @JoelLau go ahead.

**Comment by JoelLau** [comment]
sorry, this is taking longer than expected

do you happen to know an easy way to get the current route?

**Comment by humancalico** [comment]
> do you happen to know an easy way to get the current route?

I haven't looked into it yet. Maybe this piece of code would be helpful https://github.com/Charca/sapper-blog-template/blob/master/src/components/Nav.svelte

**Comment by aayushmau5** [comment]
One way would be to define a CSS class with primary color, and all other color default to gray or something, and attaching event listener for click which does the job of attaching/de-attaching the class from the nav elements.
