### ISSUE TITLE
Improve Website responsiveness

### ISSUE THREAD

**Issue by Ankurk99** [JIITODC/jiitodc.github.io#81]
## Expected Behavior
The website is expected to be displayed in the same way in all devices(mobile,pcs with different sizes)
## Actual Behavior
The top navigation bar is not properly displayed in mobile phone.

**Comment by prox07** [comment]
Until unless you take this up, I'll be closing this for the time being.

**Comment by Ankurk99** [comment]
@prox07 I was already working on the issue just mentioned it so that other are also aware and could contribute for the same.
